version: "3.7"

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
  es:
    image: elasticsearch:7.0.1
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: