
version: 2.1

executors:
  my-executor:
    docker:
      - image: node:latest
      - image: mariadb:latest
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=test # doesn't create the default database like i expect in circle

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: npm install
      - run: npx wait-on tcp:localhost:3306 --timeout 90000
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
